### ISSUE TITLE
NA results 

### ISSUE THREAD

**Issue by charliex210** [nghiavtr/BPSC#2]
Hi,
when I run BPSC for differential expressed analysis, I found many NA in the result, what is the problem?

sce = sce[rowSums(assay(sce, "normcounts")) > 0, ]
res = BPglm(data = assay(sce, "normcounts"), controlIds = controlIds, design = design, coef = coef,
            estIntPar = F, useParallel = TRUE)
> sum(is.na(res$PVAL))
[1] 1322

**Comment by nghiavtr** [comment]
Hi Charlie,

Thanks for interesting in BPSC. It is hard to explain exactly why there are many NAs in the results from your data. 
I think, the NAs are possibly produced due to 
- too many zero (>95%) in the gene/isoform expression or 
- some issues in the fitting or model can not be fitted well.

In your code, you fit the model with "normcounts", ie counts after normalisation right? Be sure that the data are NOT log-scaled.

Nghia

**Comment by charliex210** [comment]
Hi Nghia,

Thanks for your reply!

I use the normalized counts as input. I find that if the expression values in the control group are all zero, the regression model cannot be fitted, and result in NA p-value. To avoid this issue, I first calculated the fold change of each gene between two conditions and used the condition with higher expression (no zero values) as the control. I am not sure if my operation is reasonable, or there is a better solution for such situation?

Charlie

**Comment by nghiavtr** [comment]
Hi Charlie,

I think it sounds reasonable. 
If the number of zeros is too high,  you also can try the five-parameters model of BPSC that the last parameter control for the proportion of zeros. Thus, you might have better fit.

Good lucks,
Nghia
